import { CLAUDE_CREDENTIAL_ENV_VARS, GPT_SUBAGENT_MODELS, llmProxyEnv } from './llm-proxy';
import { CLAUDE_BIN_ENV } from './session-scope';

/**
 * GPT subagents: a command a Claude session runs with Bash to hand a task to a
 * GPT model, as a one-shot Claude Code agent behind the LLM proxy
 * (doc/settings.md "GPT Subagents"). A command rather than an MCP tool, so the
 * run is part of the session's process tree (reaped by Stop) and can run in the
 * background like any other command.
 */

/** Env vars carrying the proxy to the command. */
export const LLM_PROXY_URL_ENV = 'CLAWED_LLM_PROXY_URL';
export const LLM_PROXY_KEY_ENV = 'CLAWED_LLM_PROXY_KEY';
/** The session's setting sources, so the subagent loads the same settings files. */
export const SETTING_SOURCES_ENV = 'CLAWED_SETTING_SOURCES';

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/**
 * The command's bash source. Model names and the alias mapping are baked in;
 * the proxy and CLI binary come from the session's env at run time. The prompt
 * is an argument, or stdin when there is none (`claude -p` reads it).
 */
export function gptSubagentScript(): string {
  const tierCases = Object.entries(GPT_SUBAGENT_MODELS)
    .map(([tier, model]) => `  ${tier}) model=${shellQuote(model)} ;;`)
    .join('\n');
  const tiers = Object.keys(GPT_SUBAGENT_MODELS).join('|');
  // Every subagent model is in one family, so the aliases map the same for all.
  const {
    ANTHROPIC_BASE_URL: _url,
    ANTHROPIC_AUTH_TOKEN: _key,
    ...aliases
  } = llmProxyEnv(GPT_SUBAGENT_MODELS.sol, { url: '', key: undefined });
  const aliasArgs = Object.entries(aliases)
    .map(([name, value]) => `  ${name}=${shellQuote(value)} \\`)
    .join('\n');
  const unsetArgs = CLAUDE_CREDENTIAL_ENV_VARS.map((name) => `-u ${name}`).join(' ');
  return `#!/bin/bash
# Generated by clawed-abode (src/lib/gpt-subagent.ts); overwritten on every session start.
set -euo pipefail
usage() { echo "usage: $(basename "$0") <${tiers}> [prompt]   (prompt on stdin if omitted)" >&2; exit 2; }
case "\${1:-}" in
${tierCases}
  *) usage ;;
esac
shift
: "\${${LLM_PROXY_URL_ENV}:?no LLM proxy configured for this session}"
exec env ${unsetArgs} \\
  ANTHROPIC_BASE_URL="\$${LLM_PROXY_URL_ENV}" \\
  ANTHROPIC_AUTH_TOKEN="\${${LLM_PROXY_KEY_ENV}:-unused}" \\
${aliasArgs}
  "\${${CLAUDE_BIN_ENV}:-claude}" -p --model "$model" --output-format text \\
  --permission-mode bypassPermissions --allow-dangerously-skip-permissions \\
  --setting-sources "\${${SETTING_SOURCES_ENV}:-project}" \\
  "$@"
`;
}

/** Appended to a Claude session's system prompt when GPT subagents are available. */
export function gptSubagentPrompt(commandPath: string): string {
  return `You can hand a task to an OpenAI GPT-6 model by running \`${commandPath} <astra|sol|luna> "<prompt>"\` with Bash (pipe long prompts on stdin instead). It runs a one-shot agent with your tools in the current directory and prints its final answer. It knows nothing of this conversation, so give it everything it needs. Runs can take many minutes, so use run_in_background for anything substantial. Your own subagents remain the default; use these when a different model family is worth it:
- sol: strong at coding. Good for independent reviews, where a different model family catches different mistakes — e.g. a second code review alongside your own.
- luna: cheap and fast, for simple, well-defined tasks.
- astra: the strongest at conceptual math, and very expensive. Use it only for tasks that need conceptual math (proofs, derivations, checking mathematical reasoning) — never for general coding or reviews.`;
}
