packages:
  - '.'
  - 'agent-service'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - better-sqlite3
  - cpu-features
  - prisma
  - protobufjs
  - ssh2
  - unrs-resolver
